// <auto-generated />
using System;
using ChessApp.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChessApp.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260916170416_AddReviews")]
    partial class AddReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChessApp.Backend.Models.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("ix_blocks_blocked_id");

                    b.HasIndex("BlockerId")
                        .HasDatabaseName("ix_blocks_blocker_id");

                    b.HasIndex("BlockerId", "BlockedId")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_blocker_id_blocked_id");

                    b.ToTable("blocks", null, t =>
                        {
                            t.HasCheckConstraint("ck_different_users", "blocker_id != blocked_id");
                        });
                });

            modelBuilder.Entity("ChessApp.Backend.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Pgn")
                        .HasColumnType("text")
                        .HasColumnName("pgn");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("played_at");

                    b.Property<bool?>("PlayedWithBoard")
                        .HasColumnType("boolean")
                        .HasColumnName("played_with_board");

                    b.Property<Guid>("Player1Id")
                        .HasColumnType("uuid")
                        .HasColumnName("player1id");

                    b.Property<Guid>("Player2Id")
                        .HasColumnType("uuid")
                        .HasColumnName("player2id");

                    b.Property<Guid?>("ProposalId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_id");

                    b.Property<string>("TimeControl")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("time_control");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("PlayedAt")
                        .HasDatabaseName("ix_matches_played_at");

                    b.HasIndex("Player1Id")
                        .HasDatabaseName("ix_matches_player1id");

                    b.HasIndex("Player2Id")
                        .HasDatabaseName("ix_matches_player2id");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("ChessApp.Backend.Models.Proposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Point>("MeetingLocation")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("meeting_location");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("ProposerId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposer_id");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_proposals");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_proposals_expires_at");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_proposals_match_id");

                    b.HasIndex("MeetingLocation")
                        .HasDatabaseName("ix_proposals_meeting_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MeetingLocation"), "GIST");

                    b.HasIndex("ProposerId")
                        .HasDatabaseName("ix_proposals_proposer_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_proposals_status");

                    b.HasIndex("ReceiverId", "Status")
                        .HasDatabaseName("ix_proposals_receiver_id_status")
                        .HasFilter("status = 'pending'");

                    b.ToTable("proposals", null, t =>
                        {
                            t.HasCheckConstraint("ck_different_users", "proposer_id != receiver_id");
                        });
                });

            modelBuilder.Entity("ChessApp.Backend.Models.RatingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("captured_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("platform");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_rating_snapshots");

                    b.HasIndex("UserId", "Platform")
                        .HasDatabaseName("ix_rating_snapshots_user_id_platform");

                    b.ToTable("rating_snapshots", (string)null);
                });

            modelBuilder.Entity("ChessApp.Backend.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("ChessApp.Backend.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewee_id");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("RevieweeId")
                        .HasDatabaseName("ix_reviews_reviewee_id");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_reviews_reviewer_id");

                    b.HasIndex("MatchId", "ReviewerId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_match_id_reviewer_id");

                    b.ToTable("reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_different_users", "reviewer_id != reviewee_id");

                            t.HasCheckConstraint("ck_rating_range", "rating >= 1 AND rating <= 5");
                        });
                });

            modelBuilder.Entity("ChessApp.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AvailabilityExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("availability_expires_at");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<int?>("ChessComRating")
                        .HasColumnType("integer")
                        .HasColumnName("chess_com_rating");

                    b.Property<string>("ChessComUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("chess_com_url");

                    b.Property<string>("ChessComUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chess_com_username");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceTokens")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_tokens");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FideId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("fide_id");

                    b.Property<int?>("FideRating")
                        .HasColumnType("integer")
                        .HasColumnName("fide_rating");

                    b.Property<DateTime?>("FideRatingUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fide_rating_updated_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("HasBoard")
                        .HasColumnType("boolean")
                        .HasColumnName("has_board");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<DateTime?>("LastLocationUpdate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_location_update");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login");

                    b.Property<int?>("LichessRating")
                        .HasColumnType("integer")
                        .HasColumnName("lichess_rating");

                    b.Property<string>("LichessUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("lichess_url");

                    b.Property<string>("LichessUsername")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lichess_username");

                    b.Property<Point>("Location")
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AvailabilityExpiresAt")
                        .HasDatabaseName("ix_users_availability_expires_at")
                        .HasFilter("is_available = true");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("ix_users_is_available")
                        .HasFilter("is_available = true");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_users_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "GIST");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ChessApp.Backend.Models.UserStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AvgOpponentRating")
                        .HasColumnType("integer")
                        .HasColumnName("avg_opponent_rating");

                    b.Property<DateTime>("LastStatsUpdate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_stats_update")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer")
                        .HasColumnName("longest_streak");

                    b.Property<int>("TotalDraws")
                        .HasColumnType("integer")
                        .HasColumnName("total_draws");

                    b.Property<int>("TotalLosses")
                        .HasColumnType("integer")
                        .HasColumnName("total_losses");

                    b.Property<int>("TotalMatchesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("total_matches_played");

                    b.Property<int>("TotalWins")
                        .HasColumnType("integer")
                        .HasColumnName("total_wins");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_stats");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_stats_user_id");

                    b.ToTable("user_stats", (string)null);
                });

            modelBuilder.Entity("ChessApp.Backend.Models.Block", b =>
                {
                    b.HasOne("ChessApp.Backend.Models.User", "Blocked")
                        .WithMany("BlockedBy")
                        .HasForeignKey("BlockedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_users_blocked_id");

                    b.HasOne("ChessApp.Backend.Models.User", "Blocker")
                        .WithMany("Blocking")
                        .HasForeignKey("BlockerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_users_blocker_id");

                    b.Navigation("Blocked");

                    b.Navigation("Blocker");
                });

            modelBuilder.Entity("ChessApp.Backend.Models.Match", b =>
                {
                    b.HasOne("ChessApp.Backend.Models.User", "Player1")
                        .WithMany("MatchesAsPlayer1")
                        .HasForeignKey("Player1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_users_player1id");

                    b.HasOne("ChessApp.Backend.Models.User", "Player2")
                        .WithMany("MatchesAsPlayer2")
                        .HasForeignKey("Player2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_users_player2id");

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });

            modelBuilder.Entity("ChessApp.Backend.Models.Proposal", b =>
                {
                    b.HasOne("ChessApp.Backend.Models.Match", "Match")
                        .WithOne("Proposal")
                        .HasForeignKey("ChessApp.Backend.Models.Proposal", "MatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_proposals_matches_match_id");

                    b.HasOne("ChessApp.Backend.Models.User", "Proposer")
                        .WithMany("ProposalsSent")
                        .HasForeignKey("ProposerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposals_users_proposer_id");

                    b.HasOne("ChessApp.Backend.Models.User", "Receiver")
                        .WithMany("ProposalsReceived")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposals_users_receiver_id");

                    b.Navigation("Match");

                    b.Navigation("Proposer");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("ChessApp.Backend.Models.RatingSnapshot", b =>
                {
                    b.HasOne("ChessApp.Backend.Models.User", "User")
                        .WithMany("RatingSnapshots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rating_snapshots_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChessApp.Backend.Models.RefreshToken", b =>
                {
                    b.HasOne("ChessApp.Backend.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChessApp.Backend.Models.Review", b =>
                {
                    b.HasOne("ChessApp.Backend.Models.Match", "Match")
                        .WithMany("Reviews")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_matches_match_id");

                    b.HasOne("ChessApp.Backend.Models.User", "Reviewee")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_reviewee_id");

                    b.HasOne("ChessApp.Backend.Models.User", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_reviewer_id");

                    b.Navigation("Match");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ChessApp.Backend.Models.UserStats", b =>
                {
                    b.HasOne("ChessApp.Backend.Models.User", "User")
                        .WithOne("Stats")
                        .HasForeignKey("ChessApp.Backend.Models.UserStats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_stats_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChessApp.Backend.Models.Match", b =>
                {
                    b.Navigation("Proposal");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("ChessApp.Backend.Models.User", b =>
                {
                    b.Navigation("BlockedBy");

                    b.Navigation("Blocking");

                    b.Navigation("MatchesAsPlayer1");

                    b.Navigation("MatchesAsPlayer2");

                    b.Navigation("ProposalsReceived");

                    b.Navigation("ProposalsSent");

                    b.Navigation("RatingSnapshots");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
